FROM debian:bookworm-slim

RUN useradd --create-home --uid 10001 skoosh
WORKDIR /app
COPY build/server/skoosh-server.x86_64 /app/skoosh-server
RUN chmod 0755 /app/skoosh-server && chown skoosh:skoosh /app/skoosh-server

USER skoosh
EXPOSE 9077/udp
ENTRYPOINT ["/app/skoosh-server", "--headless", "--", "--server", "--port=9077"]
